USE [21291001_ETL];
GO

SELECT TABLE_NAME, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('raw_customers_dirty', 'raw_products_dirty', 'raw_leads_dirty')
ORDER BY TABLE_NAME, ORDINAL_POSITION;